// Permit seed data for Colorado river corridors.
// Each record covers one corridor's primary permit situation.
// Required: true  = boaters must obtain the permit listed.
// Required: false = no permit needed; detail explains access rules.
// Do NOT import or use this file in resources/ — Seed.ts integration is handled separately.

export const PERMITS = [
	{
		id: 'permit-arkansas-headwaters',
		corridorId: 'arkansas-headwaters',
		name: 'Arkansas Headwaters Recreation Area — Colorado Parks Pass',
		agency: 'Colorado Parks & Wildlife (CPW)',
		required: true,
		feeUsd: 8.00,
		feeNote: '$8/day per vehicle at AHRA access sites; Annual Parks Pass ($80) covers all CPW sites',
		seasonStartMonth: 4,
		seasonEndMonth: 9,
		season: 'Apr–Sep',
		detail: 'A Colorado Parks Pass (daily or annual) is required to launch or take out at all managed Arkansas Headwaters Recreation Area access sites. Purchase at site self-pay stations or online at cpw.state.co.us. Commercial outfitters hold separate AHRA commercial use permits issued by CPW. No advance reservation required for private boaters.',
		url: 'https://cpw.state.co.us/placestogo/parks/ArkansasHeadwatersRecreationArea',
		lastVerifiedAt: null,
		verifiedBy: null,
		currentContributionId: null,
	},
	{
		id: 'permit-gunnison-gorge',
		corridorId: 'gunnison-gorge-corridor',
		name: 'Gunnison Gorge Wilderness Boating Permit',
		agency: 'Bureau of Land Management (BLM) — Uncompahgre Field Office',
		required: true,
		feeUsd: 0.00,
		feeNote: 'No fee — self-registration at trailhead',
		seasonStartMonth: 4,
		seasonEndMonth: 10,
		season: 'Apr–Oct',
		detail: 'Private boaters must complete a free self-issue permit at the North Fork trailhead before launching into the Gunnison Gorge Wilderness. Group size is limited to 15 persons. Camping is limited to designated sites. Fires are prohibited below the canyon rim. No advance reservation required; permits are first-come, first-served. Motorized boats prohibited.',
		url: 'https://www.blm.gov/visit/gunnison-gorge-national-conservation-area',
		lastVerifiedAt: null,
		verifiedBy: null,
		currentContributionId: null,
	},
	{
		id: 'permit-ruby-horsethief',
		corridorId: 'ruby-horsethief',
		name: 'Ruby-Horsethief Canyon — BLM Group Size Compliance',
		agency: 'Bureau of Land Management (BLM) — Grand Junction Field Office',
		required: false,
		feeUsd: null,
		feeNote: null,
		seasonStartMonth: 3,
		seasonEndMonth: 11,
		season: 'Mar–Nov',
		detail: 'No permit required for private boaters on the Ruby-Horsethief reach (Loma to Westwater). Group size is limited to 25 persons. Campsites are first-come, first-served; pack out all waste. A free self-registration form is available at the Loma boat launch kiosk for BLM tracking purposes but is not legally required.',
		url: 'https://www.blm.gov/visit/ruby-horsethief-canyon',
		lastVerifiedAt: null,
		verifiedBy: null,
		currentContributionId: null,
	},
	{
		id: 'permit-yampa-dinosaur',
		corridorId: 'yampa-corridor',
		name: 'Dinosaur National Monument — Yampa River Permit',
		agency: 'National Park Service (NPS) — Dinosaur National Monument',
		required: true,
		feeUsd: 20.00,
		feeNote: '$20/person non-refundable application fee; additional $6/person/night river use fee',
		seasonStartMonth: 5,
		seasonEndMonth: 6,
		season: 'May–Jun',
		detail: 'A mandatory NPS launch permit is required for all private boaters on the Yampa River through Dinosaur National Monument (Deerlodge Park to Echo Park and beyond). Permits are lottery-allocated; applications open in January for the upcoming season via recreation.gov. Launch dates and group sizes are fixed at permit issuance. The Yampa is free-flowing — the season window is narrow (typically May through mid-June depending on snowmelt). Commercial trips run under separate outfitter permits.',
		url: 'https://www.nps.gov/dino/planyourvisit/whitewaterrafting.htm',
		lastVerifiedAt: null,
		verifiedBy: null,
		currentContributionId: null,
	},
	{
		id: 'permit-upper-colorado',
		corridorId: 'upper-colorado',
		name: 'Upper Colorado — No Permit Required',
		agency: 'Bureau of Land Management (BLM)',
		required: false,
		feeUsd: null,
		feeNote: null,
		seasonStartMonth: 5,
		seasonEndMonth: 9,
		season: 'May–Sep',
		detail: 'No permit required for private boaters on the Pumphouse–State Bridge corridor. Access sites are managed by BLM. Commercial outfitters require a BLM commercial use permit. Campfire restrictions apply in the riparian zone during fire season.',
		url: 'https://www.blm.gov/visit/pumphouse-recreation-site',
		lastVerifiedAt: null,
		verifiedBy: null,
		currentContributionId: null,
	},
	{
		id: 'permit-clear-creek-canyon',
		corridorId: 'clear-creek-canyon',
		name: 'Clear Creek Canyon — No Permit Required',
		agency: 'Colorado Parks & Wildlife / Jefferson County Open Space',
		required: false,
		feeUsd: null,
		feeNote: null,
		seasonStartMonth: 4,
		seasonEndMonth: 7,
		season: 'Apr–Jul',
		detail: 'No permit required for private boaters on Clear Creek. Public access points are managed by Jefferson County Open Space and CDOT. Commercial outfitters operating on the lower canyon require a county commercial use authorization. The creek corridor follows US-6 — parking at launch sites is limited.',
		url: 'https://www.jeffco.us/1332/Clear-Creek-Canyon',
		lastVerifiedAt: null,
		verifiedBy: null,
		currentContributionId: null,
	},
	{
		id: 'permit-poudre-canyon',
		corridorId: 'poudre-canyon',
		name: 'Cache La Poudre Wild & Scenic River — No Permit Required',
		agency: 'U.S. Forest Service — Roosevelt National Forest',
		required: false,
		feeUsd: null,
		feeNote: null,
		seasonStartMonth: 5,
		seasonEndMonth: 7,
		season: 'May–Jul',
		detail: "No permit required for private boaters on Colorado's only Wild and Scenic River. Access sites are managed by the USFS and Larimer County. Commercial outfitters require a Special Use Permit from the Roosevelt National Forest. The river corridor follows CO-14 with multiple public pullouts. Respect all posted private property boundaries at takeouts.",
		url: 'https://www.fs.usda.gov/recarea/arp/recarea/?recid=28180',
		lastVerifiedAt: null,
		verifiedBy: null,
		currentContributionId: null,
	},
	{
		id: 'permit-dolores-canyon',
		corridorId: 'dolores-canyon',
		name: 'Dolores River Canyon — BLM Self-Registration',
		agency: 'Bureau of Land Management (BLM) — Dolores Field Office',
		required: false,
		feeUsd: null,
		feeNote: null,
		seasonStartMonth: 4,
		seasonEndMonth: 5,
		season: 'Apr–May',
		detail: 'No advance permit required for private boaters on the Dolores River through Slick Rock and Gateway canyons. Boaters are encouraged to complete a free self-registration form at the Bradfield Bridge launch site for BLM trip tracking and search-and-rescue purposes. Group size limits (25 persons) and campfire restrictions apply. Boatability is entirely dependent on McPhee Dam releases — check release schedules before planning a trip.',
		url: 'https://www.blm.gov/visit/dolores-river-canyon',
		lastVerifiedAt: null,
		verifiedBy: null,
		currentContributionId: null,
	},
];
